export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const LOGIN_CALL_START = "LOGIN_CALL_START";
export const LOGIN_NETWORK_ERROR = "LOGIN_NETWORK_ERROR";
export const LOGIN_SUCESSFULL = "LOGIN_SUCESSFULL";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_CALL_START = "LOGOUT_CALL_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";